# Generated by Django 2.0 on 2017-12-09 22:49

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_profile_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image_size',
            field=image_cropping.fields.ImageRatioField('image', '450x550', adapt_rotation=False, allow_fullsize=True, free_crop=True, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image size'),
        ),
    ]
