# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-06 22:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('created_by',
                 models.BigIntegerField()),
                ('changed_by',
                 models.BigIntegerField()),
                ('created_at',
                 models.DateTimeField(
                     default=django.utils.timezone.now)),
                ('changed_at',
                 models.DateTimeField(
                     default=django.utils.timezone.now)),
                ('id',
                 models.BigAutoField(
                     primary_key=True,
                     serialize=False)),
                ('src',
                 models.ImageField(
                     upload_to='images/')),
                ('title',
                 models.CharField(
                     max_length=255,
                     verbose_name='title')),
                ('target',
                 models.TextField(
                     blank=True,
                     max_length=255,
                     null=True,
                     verbose_name='target url')),
                ('description',
                 models.TextField(
                     blank=True,
                     max_length=255,
                     null=True,
                     verbose_name='description')),
                ('attributes',
                 django.contrib.postgres.fields.jsonb.JSONField(
                     blank=True,
                     null=True)),
                ('post_size',
                 image_cropping.fields.ImageRatioField(
                     'src',
                     '450x550',
                     adapt_rotation=False,
                     allow_fullsize=True,
                     free_crop=True,
                     help_text=None,
                     hide_image_field=False,
                     size_warning=False,
                     verbose_name='post size')),
                ('post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='images',
                     to='post.Post')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_image',
            },
        ),
    ]
